version: '3.2'

services:
  rabbitmq-service:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    container_name: 'rabbitmq-container'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  service-producer:
    build:
      context: ./service-1/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - RABBITMQ=amqp://admin:admin@rabbitmq-service:5672
    container_name: 'service-producer-container'
  service-consumer:
    build:
      context: ./service-2/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - RABBITMQ=amqp://admin:admin@rabbitmq-service:5672
    container_name: 'service-consumer-container'
